// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.pj.core.msg;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 版本 
     * </pre>
     *
     * <code>fixed32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 模块 
     * </pre>
     *
     * <code>fixed32 module = 2;</code>
     */
    int getModule();

    /**
     * <pre>
     * 状态 
     * </pre>
     *
     * <code>fixed32 stat = 3;</code>
     */
    int getStat();

    /**
     * <pre>
     * 序号 
     * </pre>
     *
     * <code>fixed32 serial = 4;</code>
     */
    int getSerial();

    /**
     * <pre>
     * 内容 
     * </pre>
     *
     * <code>bytes body = 15;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * <pre>
   ******************* 头部 **************************
   * </pre>
   *
   * Protobuf type {@code msg.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              version_ = input.readFixed32();
              break;
            }
            case 21: {

              module_ = input.readFixed32();
              break;
            }
            case 29: {

              stat_ = input.readFixed32();
              break;
            }
            case 37: {

              serial_ = input.readFixed32();
              break;
            }
            case 122: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.pj.core.msg.MessageProto.internal_static_msg_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.pj.core.msg.MessageProto.internal_static_msg_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.pj.core.msg.MessageProto.Message.class, org.pj.core.msg.MessageProto.Message.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     * 版本 
     * </pre>
     *
     * <code>fixed32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int MODULE_FIELD_NUMBER = 2;
    private int module_;
    /**
     * <pre>
     * 模块 
     * </pre>
     *
     * <code>fixed32 module = 2;</code>
     */
    public int getModule() {
      return module_;
    }

    public static final int STAT_FIELD_NUMBER = 3;
    private int stat_;
    /**
     * <pre>
     * 状态 
     * </pre>
     *
     * <code>fixed32 stat = 3;</code>
     */
    public int getStat() {
      return stat_;
    }

    public static final int SERIAL_FIELD_NUMBER = 4;
    private int serial_;
    /**
     * <pre>
     * 序号 
     * </pre>
     *
     * <code>fixed32 serial = 4;</code>
     */
    public int getSerial() {
      return serial_;
    }

    public static final int BODY_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     * 内容 
     * </pre>
     *
     * <code>bytes body = 15;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeFixed32(1, version_);
      }
      if (module_ != 0) {
        output.writeFixed32(2, module_);
      }
      if (stat_ != 0) {
        output.writeFixed32(3, stat_);
      }
      if (serial_ != 0) {
        output.writeFixed32(4, serial_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(15, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, version_);
      }
      if (module_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, module_);
      }
      if (stat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, stat_);
      }
      if (serial_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, serial_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.pj.core.msg.MessageProto.Message)) {
        return super.equals(obj);
      }
      org.pj.core.msg.MessageProto.Message other = (org.pj.core.msg.MessageProto.Message) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getModule()
          != other.getModule()) return false;
      if (getStat()
          != other.getStat()) return false;
      if (getSerial()
          != other.getSerial()) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + MODULE_FIELD_NUMBER;
      hash = (53 * hash) + getModule();
      hash = (37 * hash) + STAT_FIELD_NUMBER;
      hash = (53 * hash) + getStat();
      hash = (37 * hash) + SERIAL_FIELD_NUMBER;
      hash = (53 * hash) + getSerial();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.pj.core.msg.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.pj.core.msg.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.pj.core.msg.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.pj.core.msg.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.pj.core.msg.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ******************* 头部 **************************
     * </pre>
     *
     * Protobuf type {@code msg.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.Message)
        org.pj.core.msg.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.pj.core.msg.MessageProto.internal_static_msg_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.pj.core.msg.MessageProto.internal_static_msg_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.pj.core.msg.MessageProto.Message.class, org.pj.core.msg.MessageProto.Message.Builder.class);
      }

      // Construct using org.pj.core.msg.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        module_ = 0;

        stat_ = 0;

        serial_ = 0;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.pj.core.msg.MessageProto.internal_static_msg_Message_descriptor;
      }

      @java.lang.Override
      public org.pj.core.msg.MessageProto.Message getDefaultInstanceForType() {
        return org.pj.core.msg.MessageProto.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.pj.core.msg.MessageProto.Message build() {
        org.pj.core.msg.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.pj.core.msg.MessageProto.Message buildPartial() {
        org.pj.core.msg.MessageProto.Message result = new org.pj.core.msg.MessageProto.Message(this);
        result.version_ = version_;
        result.module_ = module_;
        result.stat_ = stat_;
        result.serial_ = serial_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.pj.core.msg.MessageProto.Message) {
          return mergeFrom((org.pj.core.msg.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.pj.core.msg.MessageProto.Message other) {
        if (other == org.pj.core.msg.MessageProto.Message.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getModule() != 0) {
          setModule(other.getModule());
        }
        if (other.getStat() != 0) {
          setStat(other.getStat());
        }
        if (other.getSerial() != 0) {
          setSerial(other.getSerial());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.pj.core.msg.MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.pj.core.msg.MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * 版本 
       * </pre>
       *
       * <code>fixed32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 版本 
       * </pre>
       *
       * <code>fixed32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 版本 
       * </pre>
       *
       * <code>fixed32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int module_ ;
      /**
       * <pre>
       * 模块 
       * </pre>
       *
       * <code>fixed32 module = 2;</code>
       */
      public int getModule() {
        return module_;
      }
      /**
       * <pre>
       * 模块 
       * </pre>
       *
       * <code>fixed32 module = 2;</code>
       */
      public Builder setModule(int value) {
        
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 模块 
       * </pre>
       *
       * <code>fixed32 module = 2;</code>
       */
      public Builder clearModule() {
        
        module_ = 0;
        onChanged();
        return this;
      }

      private int stat_ ;
      /**
       * <pre>
       * 状态 
       * </pre>
       *
       * <code>fixed32 stat = 3;</code>
       */
      public int getStat() {
        return stat_;
      }
      /**
       * <pre>
       * 状态 
       * </pre>
       *
       * <code>fixed32 stat = 3;</code>
       */
      public Builder setStat(int value) {
        
        stat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态 
       * </pre>
       *
       * <code>fixed32 stat = 3;</code>
       */
      public Builder clearStat() {
        
        stat_ = 0;
        onChanged();
        return this;
      }

      private int serial_ ;
      /**
       * <pre>
       * 序号 
       * </pre>
       *
       * <code>fixed32 serial = 4;</code>
       */
      public int getSerial() {
        return serial_;
      }
      /**
       * <pre>
       * 序号 
       * </pre>
       *
       * <code>fixed32 serial = 4;</code>
       */
      public Builder setSerial(int value) {
        
        serial_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 序号 
       * </pre>
       *
       * <code>fixed32 serial = 4;</code>
       */
      public Builder clearSerial() {
        
        serial_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 内容 
       * </pre>
       *
       * <code>bytes body = 15;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       * 内容 
       * </pre>
       *
       * <code>bytes body = 15;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容 
       * </pre>
       *
       * <code>bytes body = 15;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.Message)
    }

    // @@protoc_insertion_point(class_scope:msg.Message)
    private static final org.pj.core.msg.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.pj.core.msg.MessageProto.Message();
    }

    public static org.pj.core.msg.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.pj.core.msg.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\003msg\"V\n\007Message\022\017\n\007versi" +
      "on\030\001 \001(\007\022\016\n\006module\030\002 \001(\007\022\014\n\004stat\030\003 \001(\007\022\016" +
      "\n\006serial\030\004 \001(\007\022\014\n\004body\030\017 \001(\014B\037\n\017org.pj.c" +
      "ore.msgB\014MessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_msg_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msg_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_Message_descriptor,
        new java.lang.String[] { "Version", "Module", "Stat", "Serial", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
